### ISSUE TITLE
A Scala's `akka-sample-cluster-kubernetes-scala` version of this

### ISSUE THREAD

**Issue by max8github** [akka/akka-sample-cluster-kubernetes-java#14]
### Short description
Would it be interesting to have this in Scala? But in that case, would I branch off of this or fork into a differently named project (`akka-sample-cluster-kubernetes-scala`)?

**Comment by max8github** [comment]
Created [akka-sample-cluster-kubernetes-scala](https://github.com/max8github/akka-sample-cluster-kubernetes-scala)

**Comment by raboof** [comment]
Hey, sorry for not responding earlier (also to your other open PR's) - this is looking pretty great, I'll dive in in more detail after the weekend!

**Comment by raboof** [comment]
I agree a separate repository is the way to go here, so :+1:

**Comment by max8github** [comment]
Ok, great, not a problem! Then that is already available here for review:  [akka-sample-cluster-kubernetes-scala](https://github.com/max8github/akka-sample-cluster-kubernetes-scala).
But...should i make you a committer to that repo for review or something? 
I guess what i am asking is: what are the next steps so to make it available from the lightbend download page ([like this one](https://developer.lightbend.com/start/?group=akka&project=akka-samples-cluster-scala))?
I suppose i have to read [here](https://developer.lightbend.com) first, which I will do, but thought i asked for quick direction...

**Comment by raboof** [comment]
> what are the next steps so to make it available from the lightbend download page (like this one)?

I think it might make sense to add it to the 'akka' organisation - I'll see if I can create it there and add you as a collaborator, if you are OK with that of course? Some of the tooling behind developer.lightbend.com isn't publicly available, I'll make sure it gets pushed through to there.

**Comment by max8github** [comment]
> I think it might make sense to add it to the 'akka' organisation
yes
> - I'll see if I can create it there and add you as a collaborator, if you are OK with that of course?
sure thing, whatever works

**Comment by raboof** [comment]
It's also on https://developer.lightbend.com/start/?group=akka now - thanks again, looking forward to collaborating more!
