### ISSUE TITLE
Docker for Desktop instructions and minor edits.

### ISSUE THREAD

**Issue by max8github** [akka/akka-sample-cluster-kubernetes-java#15]
### Short description

Would it be ok for me to contribute instructions for Kubernetes on Docker desktop in addition to Minikube?
Going to try that in a next PR, and see where it goes (and going to read contrib guidelines, which i have not yet)...

Another thing i noticed is that in the current code `ClusterWatcher` is not used and sbt is not used (mvn is).

**Comment by raboof** [comment]
Thanks!
